server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
# Le dice a Nginx (el servidor web que va a servir tu frontend) cómo manejar las peticiones.